### ISSUE TITLE
threejs base vertex shader global variables not working

### ISSUE THREAD

**Issue by snake89322** [hsimpson/vscode-glsllint#39] opened 2021-11-30 03:42 UTC
```Base.vert
void main(void) {
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.);
}
```

glsl lint error:
'projectionMatrix' : undeclared identifier 
'' : compilation terminated 

how to disable the lint or declare global variable.

**Comment by hsimpson** [comment] 2021-12-01 18:42
Duplicate of #27

**Closed by hsimpson** 2021-12-01 18:42 UTC

**Comment by jkiss** [comment] 2023-04-13 09:49
just uninstall this plugin 🥲
